# reference: http://www.objc.io/issue-6/travis-ci.html

osx_image: xcode8
language: objective-c
rvm: 2.2.2

before_install:
- sudo gem install cocoapods --pre
- cd Example && rm -rf Pods && pod install && cd -
script:
- xctool test -workspace Example/URBNConvenience.xcworkspace -scheme URBNConvenience -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
